function createfigure2(X1, YMatrix1)
%CREATEFIGURE2(X1, YMatrix1)
%  X1:  vector of plot x data
%  YMATRIX1:  matrix of plot y data

%  Auto-generated by MATLAB on 22-Apr-2024 01:36:24

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple line objects using matrix input to plot
plot1 = plot(X1,YMatrix1,'LineWidth',3,'Color',[0 0 0]);
set(plot1(1),'DisplayName','Выходной сигнал');
set(plot1(2),'DisplayName','Входной сигнал','LineStyle','--');

% Create ylabel
ylabel('Амплитуда','FontName','Times New Roman');

% Create xlabel
xlabel('Время, с','FontName','Times New Roman');

box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontName','Times New Roman','FontSize',14,'GridAlpha',1,...
    'GridColor',[0 0 0],'XGrid','on','YGrid','on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','none','FontSize',14);

